### ISSUE TITLE
Randomize P-Rep list order

### ISSUE THREAD

**Issue by markdjones** [ReliantNode/myiconwallet-react#17]
- Randomize P-Rep list order. Currently top voted P-Reps are displayed first.

![image](https://user-images.githubusercontent.com/3699611/67526477-9a29c480-f700-11e9-932b-c2f4f0b1a456.png)

**Comment by qualitymanifest** [comment]
I'd like to give this one a try. I was thinking of saving a fisher-yates function in the utils directory and using that [here](https://github.com/ReliantNode/myiconwallet-react/blob/e2f366b07619a4170fb7a05d88b050c4b7f840a5/src/pages/Vote.jsx#L55)

**Comment by qualitymanifest** [comment]
Ah, I hadn't seen the note about the FA pro token being necessary. Assuming there's no way around that, I won't be able to work on this, sorry.

**Comment by bkbooth** [comment]
We've already got `lodash-es` as a dependency and it looks like `_.shuffle` uses fisher-yates so I'd recommend just using their shuffle than adding a util for it. But yeah, go for it.

If you have any trouble with the FA pro dependency, branch off `use-fontawesome-free` because I think we'll need to get that merged in today.

**Comment by qualitymanifest** [comment]
Sounds good, will do.

**Comment by bkbooth** [comment]
We just merged the `use-fontawesome-free` branch, so feel free to rebase to `master`.
